name: "Barecheck - Code Duplication"
description: "GitHub Action that posts generates code duplication reports"
branding:
  icon: "check-circle"
  color: "yellow"
inputs:
  barecheck-github-app-token:
    description: Barecheck application token, received after application installation
    required: true
  barecheck-api-key:
    description: Barecheck project API key
    required: false
  lines-threshold:
    description: "Minimum code duplications lines threshold percentage that would fail a build once it reached"
    default: "1"
    required: false
  send-summary-comment:
    description: "Send Github Pull request comment with code duplications summary"
    default: ""
    required: false
outputs:
  percentage:
    description: "Total Percentage duplication"
runs:
  using: "node12"
  main: "dist/index.js"
