name: Code Duplications

on: [pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.1

      # Testing beta of code coverage checks
      # This part can be removed or optimized once barecheck code coverage will be out of beta
      - name: Generate Code Duplications report
        id: code-coverage
        uses: ./
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          barecheck-api-key: ${{ secrets.BARECHECK_API_KEY }}
          lines-threshold: 10
          send-summary-comment: true
